(function(){
  'use strict';
  const $=id=>document.getElementById(id),W=DuelWall,R=DuelRules,renderer=DuelRender.create($('board'));
  const host=DuelHost.create(()=>window.pet),feedback=DuelFeedback.create(),motion=DuelMotion.create();
  let motionShape='',motionBounds=null,moveAgain=false;
  const S={poseRevision:0,editor:null,editorConfirmed:false,editorSignature:'',currentName:'',sourceError:false,posePending:false,matchPet:null,pet:null,source:'current',sdkContext:null,adapter:null,sessionEnded:false,scalePreference:load('duel-scale')||85,signature:'',preview:0,base:'',connected:false,info:null,limits:R.limits,rules:R.rules,session:null,snapshot:null,received:0,networkLost:false,pending:false,shotPending:false,petBusy:false,uploadBusy:false,errorCode:'',epoch:0,aim:{x:626.5,y:106.5},lastEvent:0,movePending:false,desired:null,keys:new Set(),nextMove:0};
  const messages={image_type:'请使用透明背景的 PNG 或 WebP。',file_large:'单张图片不能超过 8 MB。',image_dimensions:'图片边长需要在 16–4096 像素之间。',empty_pet:'这张图片没有可见的宠物。',pose_count:'请添加 1–3 个姿势。',source_sizes_differ:'多个姿势需要使用相同大小的原始画布。',area_small:'有效轮廓太小，无法用于公平对局。',area_large:'有效轮廓太大，无法用于公平对局。',span_small:'轮廓过于细长，请换一张完整形象。',sparse_pet:'轮廓太稀疏，请使用完整的宠物形象。',disconnected_pet:'图片有过多独立碎片，请使用连贯的宠物形象。',pose_area_difference:'各姿势的有效面积差异太大。',pose_does_not_fit:'这个姿势无法完整放进墙面。',room_not_found:'没有找到这个房间，请核对房间码。',room_full:'这个房间已有两位玩家。',unauthorized:'连接凭证已失效，请重新加入房间。',peer_left:'朋友已离开，请回到大厅重新建房。',left_room:'你已离开这个房间。',pose_cooldown:'姿势切换还在冷却，稍等一下。',shot_cooldown:'正在装填下一发。',preparing:'准备结束后就能射击。',stale_turn:'已经换边，按新回合继续吧。',stale_match:'已经开始新的一局。',rate_limited:'操作过于频繁，稍等片刻再试。',network:'暂时连接不上服务，请检查地址与网络。','current-pet-unavailable':'暂时无法读取当前桌宠，请确认当前形象可用。','idle-unavailable':'当前形象缺少待机素材。','pose-unavailable':'当前形象的素材暂时不可用。','invalid-pose-image':'当前形象的素材格式不受支持。','pose-too-large':'当前形象素材过大，暂时无法带入。',no_bridge:'请在支持读取当前形象的桌宠版本中打开这个作品。'};
  Object.assign(messages,{permission_denied:'尚未允许读取当前桌宠；可以在宿主权限入口授权，或使用自己的图片。',network_permission_denied:'尚未允许连接这个局域网地址。',CHARACTER_STATE_UNAVAILABLE:'当前形象缺少游戏需要的待机姿势。',CHARACTER_IMAGE_UNAVAILABLE:'当前形象素材暂时不可用。'});
  Object.assign(messages,{pose_locked:'初始姿势已经锁定；回到大厅可以重新摆姿势。',pose_unconfirmed:'先确认初始姿势，再进入对决。',invalid_realtime:'当前玩偶暂不支持编辑，请使用 2D 形象。',invalid_doll_realtime:'玩偶资源不完整，请重新应用形象后再试。',invalid_appearance:'玩偶资源无法读取，请重新应用形象后再试。',webgl_unavailable:'当前设备无法打开 3D 编辑，请使用 2D 形象。'});
  Object.assign(messages,{no_invitation:'请从朋友发送的游戏邀请进入；也可以使用独立服务模式。',session_closed:'这场邀请已结束，请重新发送游戏邀请。',peer_offline:'朋友暂时离线，正在恢复连接。',command_timeout:'操作没有得到裁判确认，请重试。',waiting_for_peer:'正在同步双方的宠物，请稍等。',protocol_mismatch:'双方游戏版本不同，请重新发送同一份游戏。'});
  function explain(error){const code=Object.keys(messages).find(key=>error?.message===key||error?.message?.endsWith(': '+key));return messages[code]||'这次操作没有完成，请稍后再试。';}
  function notice(text,kind='error'){const n=$('notice');n.textContent=text;n.dataset.kind=kind;n.hidden=!text;}
  function invitationEnded(){S.sessionEnded=true;S.networkLost=true;S.connected=false;feedback.reset();notice(messages.session_closed);$('connection-status').textContent=messages.session_closed;$('connection-status').dataset.status='error';enableLobby();requestAnimationFrame(()=>$('notice').scrollIntoView({block:'center'}));}
  let idleSessionPoll=null;
  function observeInvitation(){
    if(!S.sdkContext||S.session||S.sessionEnded)return Promise.resolve();if(idleSessionPoll)return idleSessionPoll;
    idleSessionPoll=(async()=>{try{const batch=await window.pet.sessions.poll({cursor:0,waitMs:0});if(!S.session&&batch.transportState==='closed')invitationEnded();}catch(error){if(!S.session&&/session_closed|caller_disposed|permission_revoked|account_changed/.test(error.message))invitationEnded();}finally{idleSessionPoll=null;}})();return idleSessionPoll;
  }
  function load(key){try{return JSON.parse(localStorage.getItem(key));}catch{return null;}}
  function save(key,value){try{value===null?localStorage.removeItem(key):localStorage.setItem(key,JSON.stringify(value));}catch{ /* Playing does not depend on storage availability. */ }}
  function canonicalBase(value){let str=value.trim();if(!/^https?:\/\//i.test(str))str='http://'+str;const u=new URL(str);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw Error('network');return u.origin;}
  async function api(path,body,auth=true,base=S.base){if(S.session?.mode==='sdk'){if(path==='state')return S.snapshot;if(path==='leave')return S.adapter.close();return S.adapter.action(path,body);} const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),4500);try{const response=await fetch(base+'/api/'+path,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{'Content-Type':'application/json'}),...(auth&&S.session?{Authorization:'Bearer '+S.session.token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:controller.signal,credentials:'omit',cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error||'network');return data;}catch(e){if(e.name==='AbortError'||e instanceof TypeError)throw Error('network');throw e;}finally{clearTimeout(timer);}}
  function enableLobby(){if($('confirm-pose')){const locked=!!S.session||S.pending||S.posePending;$('confirm-pose').disabled=!S.editor||locked;$('reset-pose').disabled=!S.editor||locked;$('pose-editor-canvas').style.pointerEvents=locked?'none':'';}const ok=!S.sessionEnded&&!!S.pet&&S.connected&&!S.pending&&!S.petBusy&&!S.uploadBusy&&!S.posePending&&!S.sourceError&&(!S.editor||S.editorConfirmed);$('create').disabled=!ok;$('join').disabled=!ok;$('connect').disabled=S.pending;$('upload').disabled=S.pending||S.uploadBusy;$('use-current').disabled=S.pending;$('pet-scale').disabled=!DuelUpload.canRescale(S.pet)||!S.pet||S.pending||S.petBusy||S.uploadBusy||!!S.session;}
  function drawPoseButtons(id,interactive){const row=$(id);row.replaceChildren();if(!S.pet)return;(interactive?(S.matchPet||S.pet):S.pet).frames.forEach((frame,index)=>{const btn=document.createElement('button');btn.className='pose-card';btn.dataset.frame=String(index);btn.setAttribute('aria-pressed',String((interactive?S.snapshot?.self.frame:S.preview)===index));const c=document.createElement('canvas');c.width=c.height=96;DuelRender.preview(c,frame);btn.append(c,document.createTextNode(frame.name));if(interactive)btn.disabled=true;btn.addEventListener('click',()=>{if(interactive)return;else{S.preview=index;renderPet();}});row.append(btn);});}
  function renderPet(){if(!S.pet)return;S.preview=Math.min(S.preview,S.pet.frames.length-1);$('pet-name').textContent=S.pet.name;$('pet-source').textContent=S.editor?'3D 玩偶':S.source==='current'?'当前桌宠':'自定义形象';DuelRender.preview($('pet-preview'),S.pet.frames[S.preview]);drawPoseButtons('lobby-poses',false);$('pet-metrics').textContent=`${S.pet.frames.length} 个可选初始姿势 · 有效像素 ${S.pet.frames[S.preview].stats.area.toLocaleString()} · 入局后固定`;$('pet-status').textContent=S.editor?'正面姿势已确认；入局后只可左右移动、平面旋转':S.source==='current'?'选好初始姿势后入局；大厅会跟随换装':'选择一个初始姿势带入本局';renderScale();enableLobby();}
  function renderScale(){const pet=S.pet,choices=pet.scaleChoices||[100],slider=$('pet-scale');slider.max=choices.length-1;slider.value=choices.indexOf(pet.scalePercent);$('scale-value').textContent=(pet.scalePercent||100)+'%';$('scale-status').textContent=DuelUpload.canRescale(pet)?`整组同步 · 可选 ${choices[0]}–${choices.at(-1)}% · 入房后锁定`:'当前比例已保留；重新添加原图后可调节大小';DuelRender.wallPreview($('scale-preview'),pet.frames[S.preview]);}
  $('pet-scale').oninput=()=>{if(S.session||S.pending||S.petBusy||S.uploadBusy||!S.pet)return;try{const n=S.pet.scaleChoices[Number($('pet-scale').value)];S.pet=DuelUpload.rescale(S.pet,n,S.limits);S.scalePreference=n;save('duel-scale',n);renderPet();}catch(error){notice(explain(error));}};
  async function normalizeCurrent(result){const files=[];for(const p of result.poses){const match=/^data:(image\/(?:png|webp));base64,([A-Za-z0-9+/]+=*)$/.exec(p.dataUrl);if(!match)throw Error('image_type');const bytes=Uint8Array.from(atob(match[2]),c=>c.charCodeAt(0));files.push(new File([bytes],({idle:'站立',walk:'侧身',greet:'招手'}[p.id]||p.label)+(match[1]==='image/png'?'.png':'.webp'),{type:match[1]}));}
    // Try the complete genuine pose set first. Keep idle as the mandatory base.
    try{const pet=await DuelUpload.normalizeFiles(files,S.limits,S.scalePreference);pet.name=result.name;pet.omitted=0;return pet;}catch(error){if(files.length===1)throw error;let accepted=[files[0]],pet=await DuelUpload.normalizeFiles(accepted,S.limits,S.scalePreference);for(const f of files.slice(1)){try{const next=await DuelUpload.normalizeFiles([...accepted,f],S.limits,S.scalePreference);accepted.push(f);pet=next;}catch{ /* Only the incompatible optional pose is omitted. */ }}pet.name=result.name;pet.omitted=files.length-accepted.length;return pet;}
  }
  function disposeEditor(){S.editor?.dispose();S.editor=null;S.editorConfirmed=false;S.editorSignature='';$('pose-editor').hidden=true;$('pet-preview').hidden=false;}
  function savePose(){if(S.editor)save('duel-pose-draft',{signature:S.editorSignature,pose:S.editor.getPose(),confirmed:S.editorConfirmed});}
  function poseChanged(){if(S.session||S.pending)return;S.poseRevision++;S.editorConfirmed=false;S.pet=null;savePose();$('pose-status').textContent='姿势已修改。保持正面，确认后带入这一局。';$('pet-status').textContent='拖动手、脚、肘或膝；身体始终正对屏幕';$('pet-metrics').textContent='';$('lobby-poses').replaceChildren();$('pet-scale').disabled=true;enableLobby();}
  async function confirmPose(quiet=false){if(!S.editor||S.session||S.posePending)return;S.posePending=true;enableLobby();const editor=S.editor,epoch=S.epoch,revision=S.poseRevision;try{
    const canvas=editor.exportCanvas();const blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('invalid-pose-image')),'image/png'));
    const pet=await DuelUpload.normalizeFiles([new File([blob],'初始姿势.png',{type:'image/png'})],S.limits,S.scalePreference);
    if(epoch!==S.epoch||editor!==S.editor||S.session||revision!==S.poseRevision)return;pet.name=S.currentName;S.pet=pet;S.preview=0;S.editorConfirmed=true;savePose();renderPet();$('pose-status').textContent='初始姿势已确认。再拖动会取消确认；入局后四肢锁定。';if(!quiet)notice('姿势已确认，可以进入对决。','success');
  }catch(error){S.editorConfirmed=false;S.pet=null;$('pose-status').textContent=explain(error);notice(explain(error));}finally{S.posePending=false;enableLobby();}}
  $('confirm-pose').onclick=()=>confirmPose();$('reset-pose').onclick=()=>{if(S.editor&&!S.session&&!S.pending){S.editor.reset();poseChanged();}};
  async function currentPet(force=false){if(S.source!=='current'||S.session||S.petBusy)return;S.petBusy=true;const epoch=S.epoch;enableLobby();try{
    const result=await host.read(),realtime=await host.readRealtime();
    if(epoch!==S.epoch||S.source!=='current'||S.session)return;
    if(realtime&&realtime.key!==result.key)throw Error('current-pet-unavailable');
    const signature=result.signature+':'+(realtime?.signature||'2d');S.sourceError=false;
    // Re-reading at entry must never discard the user's in-progress pose or confirmed frame.
    if(signature===S.signature&&(S.editor||S.pet))return;
    disposeEditor();S.signature='';S.pet=null;S.currentName=result.name;S.errorCode='';S.preview=0;
    if(realtime){
      if(realtime.renderer!=='rat-doll-renderer'||realtime.dataVersion!==2)throw Error('invalid_realtime');
      const draft=load('duel-pose-draft'),saved=draft?.signature===realtime.signature?draft:null;
      S.editorSignature=realtime.signature;$('pose-editor').hidden=false;$('pet-preview').hidden=true;$('pet-name').textContent=result.name;$('pet-source').textContent='3D 玩偶';
      const editor=await DuelDoll.create({canvas:$('pose-editor-canvas'),realtime,pose:saved?.pose,onChange:poseChanged});
      if(epoch!==S.epoch||S.source!=='current'||S.session){editor.dispose();return;}S.editor=editor;S.signature=signature;poseChanged();
      if(saved?.confirmed)await confirmPose(true);
    }else{const pet=await normalizeCurrent(result);if(epoch!==S.epoch||S.source!=='current'||S.session)return;S.pet=pet;S.signature=signature;renderPet();if(pet.omitted)$('pet-status').textContent=`已带入当前形象；${pet.omitted} 个姿势未通过轮廓校验，暂不可选`;}
  }catch(error){if(epoch!==S.epoch)return;S.errorCode=error.message;S.sourceError=true;$('pet-status').textContent=explain(error);if(!S.editor){S.pet=null;S.signature='';$('pet-name').textContent='当前形象暂不可用';$('pet-metrics').textContent='';$('lobby-poses').replaceChildren();DuelRender.preview($('pet-preview'),null);DuelRender.wallPreview($('scale-preview'),null);$('scale-value').textContent='—';$('scale-status').textContent='等待有效形象';}}
  finally{S.petBusy=false;enableLobby();}}
  function freezePet(){if(S.editor&&!S.editorConfirmed)throw Error('pose_unconfirmed');if(!S.pet||S.sourceError)throw Error('current-pet-unavailable');const frame=S.pet.frames[S.preview];return {...S.pet,frames:[{...frame}],locked:true};}
  async function connect(quiet=false){if(S.session)return;try{S.base=canonicalBase($('server-address').value);S.connected=false;enableLobby();$('connection-status').textContent='正在连接…';save('duel-preferences',{base:S.base,name:$('player-name').value});await host.network(S.base);const rules=await api('rules',undefined,false);if(rules.version!==2)throw Error('network');S.limits=rules.limits;S.rules=rules.rules;S.info=await api('info',undefined,false);S.connected=true;$('server-address').value=S.base;save('duel-preferences',{base:S.base,name:$('player-name').value});$('connection-status').textContent='已连接 · 两人使用相同地址和房间码';$('connection-status').dataset.status='online';if(S.source==='current')await currentPet(true);else if(S.pet){const frames=S.pet.frames.map(f=>({size:192,rgba:Uint8Array.from(atob(f.pixels),c=>c.charCodeAt(0))}));DuelPet.inspectGroup(frames,S.limits);}if(!quiet)notice('服务已连接。','success');}catch(error){S.connected=false;$('connection-status').textContent=explain(error);$('connection-status').dataset.status='error';if(!quiet)notice(explain(error));}finally{enableLobby();}}
  async function enter(join){if(S.pending||S.uploadBusy)return;S.pending=true;enableLobby();try{if(S.source==='current'){while(S.petBusy)await new Promise(r=>setTimeout(r,30));await currentPet(true);}S.matchPet=freezePet();const name=$('player-name').value.trim()||S.pet.name;if(S.sdkContext){await observeInvitation();if(S.sessionEnded)throw Error('session_closed');await enterInvitation(name);return;}const room=$('room-code').value.trim().toUpperCase();if(join&&!/^[A-F0-9]{6}$/.test(room)){notice('请输入完整的 6 位房间码。');return;}const session=await api(join?'join':'create',{name,pet:S.matchPet,...(join?{room}:{})},false);feedback.reset();S.session={...session,base:S.base};S.snapshot=null;S.lastEvent=0;save('duel-preferences',{base:S.base,name});saveSession();drawPoseButtons('game-poses',true);notice('');$('lobby').hidden=true;$('room').hidden=false;await poll();}catch(error){notice(explain(error));}finally{S.pending=false;enableLobby();}}
  async function enterInvitation(name){
    feedback.reset();S.session={mode:'sdk',room:S.sdkContext.invitationId.slice(0,8),me:S.sdkContext.role==='host'?0:1};S.sessionEnded=false;S.snapshot=null;S.lastEvent=0;save('duel-session',null);drawPoseButtons('game-poses',true);$('lobby').hidden=true;$('room').hidden=false;$('waiting').hidden=false;$('arena').hidden=true;$('result').hidden=true;$('ready').disabled=true;$('waiting-title').textContent='正在带入双方宠物…';$('waiting-status').textContent='邀请已经绑定你和朋友，无需房间码。';$('room-number').textContent=S.session.room;$('invite').value='已与 '+S.sdkContext.peer.displayName+' 连接';
    S.adapter=DuelSessions.create(window.pet.sessions,{onState:acceptSnapshot,onConnection:status=>{S.networkLost=status!=='connected';S.sessionEnded=status==='closed';if(status==='closed')invitationEnded();renderState();if(!S.snapshot&&status==='closed')$('waiting-status').textContent=messages.session_closed;},onError:error=>{if(!['peer_offline','invalid_player'].includes(error.message))notice(explain(error));}});
    try{await S.adapter.start({name,pet:S.matchPet});notice('');}catch(error){S.adapter.dispose();S.adapter=null;S.session=null;$('room').hidden=true;$('lobby').hidden=false;throw error;}
  }
  function updateMotionSnapshot(next){
    if(next.hiding&&next.self.pose&&S.matchPet){const shape=next.generation+':'+next.self.frame+':'+next.self.pose.angle;
      if(shape!==motionShape){const frame={size:192,rgba:Uint8Array.from(atob(S.matchPet.frames[next.self.frame].pixels),c=>c.charCodeAt(0))},b=DuelGeometry.bounds(frame,next.self.pose,W);motionBounds={minX:1-b.minX,maxX:W.width-1-b.maxX};motionShape=shape;}
    }
    motion.update(next,performance.now(),motionBounds);
  }
  function acceptSnapshot(next){if(!next||!S.session)return;S.snapshot=next;S.received=Date.now();renderer.update(next);updateMotionSnapshot(next);feedback.update(next);renderState();}
  function saveSession(){if(S.session?.mode==='sdk')return;save('duel-session',{session:S.session,pet:S.pet,matchPet:S.matchPet,source:S.source,scaleBase:S.source==='custom'?DuelUpload.exportBase(S.pet):null,until:Date.now()+40000});}
  function setAim(x,y){S.aim={x:Math.max(.5,Math.min(Math.floor(W.width)-.5,x)),y:Math.max(.5,Math.min(Math.floor(W.height)-.5,y))};$('aim-x').value=Math.floor(S.aim.x);$('aim-y').value=Math.floor(S.aim.y);renderer.setAim(S.aim);}
  function usable(){return S.snapshot&&!S.networkLost&&Date.now()-S.received<2500;}
  function canHide(){return usable()&&S.snapshot.hiding&&['prepare','active'].includes(S.snapshot.phase);}
  function canShoot(){return usable()&&!S.snapshot.hiding&&S.snapshot.phase==='active'&&!S.shotPending;}
  async function command(payload,quiet=false){const s=S.snapshot;if(!s||!usable())return null;try{return await api('command',{...payload,generation:s.generation,turn:s.turn});}catch(error){if(!quiet)notice(explain(error));return null;}}
  async function pose(frame,angle){if(!canHide()||S.snapshot.self.poseRemainingMs>0)return;await command({type:'pose',frame,angle});await poll();}
  async function shoot(){if(!canShoot())return;S.shotPending=true;renderState();const s=S.snapshot,session=S.session,id=Array.from(crypto.getRandomValues(new Uint32Array(4)),v=>v.toString(16)).join('-'),payload={type:'shoot',id,x:S.aim.x,y:S.aim.y,generation:s.generation,turn:s.turn};try{let result;try{result=await api('command',payload);}catch(error){if(error.message!=='network'||S.session!==session)throw error;result=await api('command',payload);}/* Authoritative snapshot delivers the verdict to both peers. */}catch(error){notice(explain(error));}finally{S.shotPending=false;await poll();renderState();}}

  let pollBusy=false,pollTimer,lastSaved=0,lastPhase=null,lastControlTurn='';
  async function poll(){clearTimeout(pollTimer);if(S.session?.mode==='sdk'){renderState();return;}if(!S.session||pollBusy)return;pollBusy=true;const session=S.session;try{const next=await api('state');if(S.session!==session)return;S.snapshot=next;S.received=Date.now();S.networkLost=false;renderer.update(next);updateMotionSnapshot(next);feedback.update(next);if(Date.now()-lastSaved>10000){saveSession();lastSaved=Date.now();}renderState();}catch(error){if(S.session!==session)return;S.networkLost=true;if(['unauthorized','left_room','room_not_found'].includes(error.message)){resetRoom();notice(explain(error));}else{renderState();$('footer-state').textContent='连接中断，正在自动重连…';}}finally{pollBusy=false;if(S.session)pollTimer=setTimeout(poll,180);}}
  function remaining(){return S.snapshot?Math.max(0,S.snapshot.remainingMs-(Date.now()-S.received)):0;}
  function renderState(){const s=S.snapshot;if(!s)return;const controlTurn=s.generation+':'+s.turn+':'+s.hiding;if(controlTurn!==lastControlTurn){clearKeys();lastControlTurn=controlTurn;}$('room-number').textContent=S.session.room;const waiting=s.phase==='lobby';$('waiting').hidden=!waiting;$('arena').hidden=waiting;$('result').hidden=s.phase!=='ended';$('waiting-title').textContent=s.opponent?'朋友来了。准备好了吗？':'等朋友来，一起藏。';$('room-players').textContent=s.self.name+'  ×  '+(s.opponent?.name||'等候朋友');$('waiting-status').textContent=s.opponent?(s.opponent.online?(s.opponent.ready?'朋友已经准备好了。':'朋友正在准备。'):'朋友暂时离线，等待重新连接。'):'把邀请信息发给同一网络里的朋友。';const share=S.info?.lanUrls?.[0]||S.base;$('invite').value=S.session.mode==='sdk'?'已与 '+S.sdkContext.peer.displayName+' 绑定这场邀请':`服务地址 ${share}  ·  房间码 ${S.session.room}`;$('ready').disabled=s.self.ready||S.networkLost||!s.opponent;$('ready').textContent=s.self.ready?'已准备，等朋友':'我准备好了';
    $('self-name').textContent=s.self.name;$('opponent-name').textContent=s.opponent?.name||'朋友';$('self-hp').textContent=s.self.hp;$('opponent-hp').textContent=s.opponent?.hp??100;$('self-health').style.width=s.self.hp+'%';$('opponent-health').style.width=(s.opponent?.hp??100)+'%';$('turn-number').textContent=`第 ${s.turn} 回合`;$('role-title').textContent=s.phase==='ended'?'这局结束了':s.hiding?'轮到你躲藏':'轮到你寻找';$('angle-value').textContent=(s.self.pose?.angle||0)+'°';$('control-label').textContent=s.hiding?'初始姿势已锁定':'这一局带来的姿势';$('rotate-controls').hidden=!s.hiding;$('shoot-controls').hidden=s.hiding;$('precision').hidden=s.hiding;$('fire').disabled=!canShoot();$('rotate-left').disabled=$('rotate-right').disabled=!canHide()||s.self.poseRemainingMs>0;
    for(const btn of $('game-poses').children){btn.setAttribute('aria-pressed',String(Number(btn.dataset.frame)===s.self.frame));btn.disabled=true;}
    $('ammo').replaceChildren();for(let i=0;i<s.rules.shots;i++){const el=document.createElement('i');if(i>=s.ammo)el.className='used';$('ammo').append(el);}const count=document.createElement('span');count.textContent=`${s.ammo} / ${s.rules.shots}`;$('ammo').append(count);$('ammo').setAttribute('aria-label',`剩余 ${s.ammo} 发子弹`);
    $('game-hint').textContent=s.hiding?'A / D、左右方向键移动 · 四肢固定，只可平面旋转 · 半透明的墙只有你看得到':'点击墙面发射 · 方向键微调准星，空格射击 · 命中、用完三发或时间到就换边';$('footer-state').textContent=S.sessionEnded?'本次邀请已结束，请重新邀请':S.networkLost?'正在重连…':'当前局已固定你的形象 · '+(s.phase==='lobby'?'等待开始':s.phase==='paused'?'等待朋友回来':S.session.mode==='sdk'?'发送方页面正在判定本局':'双方由同一服务判定');
    if(s.phase==='ended'){const win=s.winner===null?null:s.winner===s.me;$('result-title').textContent=win===null?'这局，打了个平手。':win?'找到你啦！你赢了。':'这局输了，再藏好一点！';const reason={knockout:'有一只宠物的生命值归零了。',left:'一位玩家离开了房间。',disconnect:'朋友超过 30 秒没有重新连接。',both_disconnected:'双方连接中断。',time_limit:'6 分钟到了，按剩余生命值结算。'};$('result-detail').textContent=reason[s.reason]||'感谢一起玩这场小游戏。';$('rematch').disabled=s.self.ready||s.opponent?.left||!s.opponent?.online||S.networkLost;$('rematch-status').textContent=s.opponent?.left?'朋友已离开，回大厅再约一局。':s.self.ready?'你已准备好，等朋友再来一局。':s.opponent?.ready?'朋友已准备好再来一局。':'双方点「再来一局」就能重新开始。';}
    $('move-controls').hidden=!s.hiding;for(const btn of $('move-controls').querySelectorAll('button'))btn.disabled=!canHide();
    renderClock();if(s.phase==='ended'&&lastPhase!=='ended')requestAnimationFrame(()=>$('result').scrollIntoView({block:'center'}));lastPhase=s.phase;
  }
  function renderClock(){const s=S.snapshot;if(!s)return;const seconds=Math.ceil(remaining()/1000);$('countdown').textContent=s.phase==='ended'?'':s.phase==='paused'?`重连剩余 ${seconds} 秒`:`${s.phase==='prepare'?'准备':'剩余'} ${seconds} 秒`;
    const banner=$('stage-banner');banner.hidden=!S.networkLost&&!['prepare','paused'].includes(s.phase);banner.querySelector('strong').textContent=S.sessionEnded?'这场邀请已结束':S.networkLost?'正在重新连接…':s.phase==='paused'?'等朋友回来':`${seconds}`;banner.querySelector('span').textContent=S.sessionEnded?'请重新发送游戏邀请，再来一局':S.networkLost?'保留这一局，网络恢复后继续':s.phase==='paused'?'对局已暂停，30 秒内可继续':s.hiding?'藏好了吗？准备开始':'朋友正在躲藏，稍等一下';}
  function resetRoom(){S.adapter?.dispose();S.adapter=null;S.sessionEnded=false;feedback.reset();S.session=null;S.matchPet=null;motion.reset();motionShape='';S.snapshot=null;lastPhase=null;S.networkLost=false;S.desired=null;S.keys.clear();clearTimeout(pollTimer);save('duel-session',null);$('room').hidden=true;$('lobby').hidden=false;$('leave-dialog').close();if(S.source==='current')void currentPet(true);else renderPet();enableLobby();}
  async function leave(){try{await api('leave',{});resetRoom();notice('已离开房间。','success');}catch(error){notice('离开请求暂未送达。请保留页面重试；服务会在断线超时后结束本局。');$('leave-dialog').close();}}
  async function ready(){try{await api('ready',{});await poll();}catch(error){notice(explain(error));}}
  $('connect').onclick=()=>connect();$('create').onclick=()=>enter(false);$('join').onclick=()=>enter(true);$('ready').onclick=$('rematch').onclick=ready;$('fire').onclick=shoot;
  $('rotate-left').onclick=()=>pose(S.snapshot.self.frame,S.snapshot.self.pose.angle-15);$('rotate-right').onclick=()=>pose(S.snapshot.self.frame,S.snapshot.self.pose.angle+15);
  $('help-toggle').onclick=()=>{const hide=!$('help').hidden;$('help').hidden=hide;$('help-toggle').setAttribute('aria-expanded',String(!hide));};
  $('leave').onclick=$('back-lobby').onclick=()=>{if(S.snapshot&&['prepare','active','paused'].includes(S.snapshot.phase))$('leave-dialog').showModal();else void leave();};$('cancel-leave').onclick=()=>$('leave-dialog').close();$('confirm-leave').onclick=leave;
  $('copy-invite').onclick=async()=>{try{await navigator.clipboard.writeText($('invite').value);notice('邀请信息已复制。','success');}catch{$('invite').focus();$('invite').select();notice('邀请信息已选中，请按复制快捷键。','success');}};
  $('player-name').oninput=()=>save('duel-preferences',{base:S.base,name:$('player-name').value});
  $('upload').onchange=async e=>{const epoch=++S.epoch;S.uploadBusy=true;enableLobby();try{const pet=await DuelUpload.normalizeFiles([...e.target.files],S.limits,S.scalePreference);if(epoch!==S.epoch||S.session)return;disposeEditor();S.sourceError=false;S.source='custom';S.pet=pet;S.preview=0;renderPet();$('upload-status').textContent='自定义形象已准备好。';}catch(error){if(epoch===S.epoch)$('upload-status').textContent=explain(error);}finally{S.uploadBusy=false;e.target.value='';enableLobby();}};
  $('use-current').onclick=()=>{S.epoch++;disposeEditor();S.source='current';S.signature='';$('upload-status').textContent='';void currentPet(true);};
  for(const id of ['aim-x','aim-y'])$(id).oninput=()=>setAim(Number($('aim-x').value)+.5,Number($('aim-y').value)+.5);
  const board=$('board');
  board.addEventListener('pointerdown',e=>{const p=renderer.point(e);if(p.x<0||p.y<0||p.x>=W.width||p.y>=W.height)return;board.focus();if(canShoot()){setAim(p.x,p.y);void shoot();}});
  board.addEventListener('pointermove',e=>{if(S.snapshot&&!S.snapshot.hiding){const p=renderer.point(e);setAim(p.x,p.y);}});
  const moveCodes=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','KeyW','KeyA','KeyS','KeyD'];
  function clearKeys(){S.keys.clear();S.desired=null;void flushMove();}
  board.addEventListener('keydown',e=>{if(moveCodes.includes(e.code)||e.code==='Space'){e.preventDefault();if(e.code==='Space'){if(!e.repeat)void shoot();}else S.keys.add(e.code);}});
  board.addEventListener('keyup',e=>{S.keys.delete(e.code);S.desired=null;void flushMove();});window.addEventListener('blur',clearKeys);board.addEventListener('blur',clearKeys);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearKeys();});
  for(const button of $('move-controls').querySelectorAll('button')){
    button.addEventListener('pointerdown',e=>{if(!canHide())return;e.preventDefault();button.setPointerCapture(e.pointerId);S.keys.add(button.dataset.direction);});
    for(const name of ['pointerup','pointercancel','lostpointercapture','blur'])button.addEventListener(name,()=>{S.keys.delete(button.dataset.direction);S.desired=null;void flushMove();});
    button.addEventListener('keydown',e=>{if(['Space','Enter'].includes(e.code)){e.preventDefault();S.keys.add(button.dataset.direction);}});
    button.addEventListener('keyup',e=>{if(['Space','Enter'].includes(e.code)){S.keys.delete(button.dataset.direction);S.desired=null;void flushMove();}});
  }
  async function flushMove(){
    if(!canHide())return;if(S.movePending){moveAgain=true;return;}
    const p=motion.current();if(!p||!motion.needsSend())return;
    S.movePending=true;
    try{await command({type:'move',x:p.x,y:p.y},true);}
    finally{S.movePending=false;if(moveAgain){moveAgain=false;void flushMove();}}
  }
  setInterval(flushMove,100);
  let paintAt=performance.now();
  setInterval(()=>{void observeInvitation();if(!S.session&&S.source==='current'&&!S.pending&&!S.uploadBusy)void currentPet();},4000);
  setInterval(()=>{if(S.snapshot){renderClock();$('fire').disabled=!canShoot();}},100);
  function paint(){const at=performance.now(),dt=Math.max(0,Math.min(.05,(at-paintAt)/1000));paintAt=at;const s=S.snapshot;
    const v=DuelSessions.vector(s?.hiding?new Set([...S.keys].filter(k=>['ArrowLeft','ArrowRight','KeyA','KeyD'].includes(k))):S.keys);
    if(s&&!s.hiding&&usable()&&(v.x||v.y))setAim(S.aim.x+v.x*50*dt,S.aim.y+v.y*50*dt);
    renderer.setPose(motion.step(v.x,at,canHide()));renderer.draw();requestAnimationFrame(paint);
  }paint();
  // Read-only diagnostics are intentionally limited to what this player received.
  window.DuelClient=Object.freeze({getState:()=>JSON.parse(JSON.stringify({snapshot:S.snapshot,pet:S.pet,matchPet:S.matchPet,editor:S.editor?{pose:S.editor.getPose(),handles:S.editor.getHandles(),confirmed:S.editorConfirmed}:null,session:S.session?{room:S.session.room,me:S.session.me,base:S.session.base}:null,aim:S.aim,source:S.source,errorCode:S.errorCode,audio:feedback.diagnostics(),transport:S.adapter?.diagnostics()||null,sessionEnded:S.sessionEnded}))});
  const prefs=load('duel-preferences');$('player-name').value=prefs?.name||'';$('server-address').value=/^https?:$/.test(location.protocol)?location.origin:prefs?.base||'http://127.0.0.1:18765';setAim(626.5,106.5);
  async function boot(){
    await currentPet();
    if(window.pet?.sessions){try{S.sdkContext=await window.pet.sessions.getContext();}catch(error){if(!String(error.message).includes('permission'))notice(explain(error));}}
    if(S.sdkContext){S.connected=true;S.base='';$('connection-status').textContent='已绑定邀请 · 对手是 '+S.sdkContext.peer.displayName;$('connection-status').dataset.status='online';$('create').textContent='带着它加入对决';$('join').parentElement.hidden=true;document.querySelector('.room-actions .or').hidden=true;document.querySelector('.server-line').hidden=true;document.querySelector('label[for="server-address"]').hidden=true;document.querySelector('.setup-help').hidden=true;enableLobby();void observeInvitation();return;}
    const prior=load('duel-session');if(prior?.until>Date.now()&&prior.session&&prior.session.mode!=='sdk'&&prior.pet){S.session=prior.session;S.base=prior.session.base;S.pet=prior.pet;S.matchPet=prior.matchPet||prior.pet;DuelUpload.restoreBase(S.pet,prior.scaleBase,S.limits);S.source=prior.source||'current';$('lobby').hidden=true;$('room').hidden=false;drawPoseButtons('game-poses',true);void poll();}else{save('duel-session',null);if(!host.supported())void connect(true);}
  }
  void boot();window.addEventListener('pagehide',()=>{S.adapter?.dispose();S.editor?.dispose();});
})();
