const test=require('node:test'),assert=require('node:assert/strict'),F=require('../game/feedback');
const state=(changes={})=>({generation:1,turn:1,phase:'active',me:0,hiding:false,serverTime:1000,rules:{damage:34},events:[],...changes});
test('verdict feedback survives role change and has shooter/victim meanings',()=>{const t=F.tracker();t.update(state());const event={shot:1,at:1100,shooter:0,hit:true,brick:3,hp:66};const s=state({turn:2,phase:'prepare',hiding:true,serverTime:1200,events:[event]});const result=t.update(s);assert(result.some(m=>m.kind==='hit'&&m.text.includes('34')));assert(result.some(m=>m.kind==='role'));assert.deepEqual(t.update(s),[]);const other=F.tracker();other.update(state({me:1}));assert(other.update({...s,me:1}).some(m=>m.kind==='hurt'));});
test('reload and stale snapshots never replay old shots; rematch can show new ones',()=>{const t=F.tracker(),old={shot:1,at:1000,shooter:0,hit:false,brick:-1};assert(!t.update(state({events:[old]})).some(m=>m.kind==='miss'));assert(!t.update(state({serverTime:5000,events:[old,{...old,shot:2}]})).some(m=>m.kind==='miss'));t.update(state({generation:2,events:[]}));assert(t.update(state({generation:2,serverTime:1100,events:[{...old,shot:3}]})).some(m=>m.kind==='miss'));});
test('result appears once, including explicit loss and draw',()=>{for(const [winner,kind]of [[0,'win'],[1,'loss'],[null,'draw']]){const t=F.tracker();t.update(state());const s=state({phase:'ended',winner});assert(t.update(s).some(m=>m.kind===kind));assert.deepEqual(t.update(s),[]);}});
test('immediate rematch clears the previous round damage toast and text',()=>{
 const elements=new Map(),el=id=>{if(!elements.has(id))elements.set(id,{hidden:true,dataset:{},textContent:'',querySelector:part=>el(id+'-'+part)});return elements.get(id);};
 const prior={document:global.document,window:global.window,localStorage:global.localStorage};global.document={hidden:false,getElementById:el,addEventListener(){},removeEventListener(){}};global.window={addEventListener(){}};global.localStorage={getItem:()=>null};
 try{const feedback=F.create();feedback.update(state());feedback.update(state({phase:'ended',winner:0,serverTime:1100,events:[{shot:1,at:1100,shooter:0,hit:true,hp:0}]}));assert.equal(el('combat-toast').hidden,false);feedback.update(state({generation:2,phase:'prepare',events:[]}));assert.equal(el('combat-toast').hidden,true);assert(!el('shot-feedback').textContent.includes('生命剩余 0'));feedback.reset();}finally{for(const [key,value]of Object.entries(prior)){if(value===undefined)delete global[key];else global[key]=value;}}
});
