'use strict';
// The replay drives production Match and Canvas renderer, at native-frame cadence.
// Historical audit runs deliberately assert the original failure, not a pass fix.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(process.env.PET_DUEL_AUDIT_ROOT||path.join(__dirname,'..')),W=require(path.join(root,'game/wall')),G=require(path.join(root,'game/geometry')),R=require(path.join(root,'game/rules')),{Match}=require(path.join(root,'game/match.cjs'));
const baseline=process.env.PET_DUEL_MOTION_BASELINE==='1',Motion=fs.existsSync(path.join(root,'game/motion.js'))?require(path.join(root,'game/motion.js')):null;
function renderer(){let clock=0,marker=null,draw=null,centroid=null,pixelCount=0;const noop=()=>{},ctx=new Proxy({arc(x,y,r){if(r===7)marker={x,y};},drawImage(c,x,y){draw={x:centroid?.x+x,y:centroid?.y+y,offsetX:x,offsetY:y,pixels:pixelCount};},createImageData:(w,h)=>({width:w,height:h,data:new Uint8ClampedArray(w*h*4)}),putImageData(img){let sx=0,sy=0,n=0;for(let i=3;i<img.data.length;i+=4)if(img.data[i]){const p=(i-3)/4;sx+=p%img.width;sy+=Math.floor(p/img.width);n++;}pixelCount=n;centroid={x:n?sx/n:0,y:n?sy/n:0};}},{get:(o,k)=>k in o?o[k]:noop});const sandbox={DuelWall:W,document:{createElement:()=>({getContext:()=>ctx})},Date:{now:()=>clock},performance:{now:()=>clock},console};sandbox.globalThis=sandbox;vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(root,'game/render.js'),'utf8'),sandbox);const r=sandbox.DuelRender.create({getContext:()=>ctx});return{r,paint(t){clock=t;marker=null;r.draw();return {marker,body:{...draw}};},update(s,t){clock=t;r.update(s);}};}
function fixture(){let time=0;const rgba=new Uint8Array(192*192*4);for(let y=20;y<172;y++)for(let x=64;x<128;x++)rgba.set([220,100,60,255],(y*192+x)*4);const frame={size:192,rgba},m=new Match(R.rules,()=>time,0);m.add('a',[frame]);m.add('b',[frame]);m.ready(0);m.ready(1);return{m,frame,set(t){time=t;m.touch(0);m.touch(1);m.tick();}};}
function metrics(points){const d=points.slice(1).map((p,i)=>Math.hypot(p.x-points[i].x,p.y-points[i].y));return{frames:d.length,movingRatio:d.filter(x=>x>.01).length/d.length,maxStep:Math.max(...d)};}
const report={root,status:baseline?'reproduced':'fixed-local-presentation'};
for(const period of [100,180,300])test(`actual own body and marker at ${period}ms snapshots`,()=>{const f=fixture(),r=renderer(),points=[],body=[],local=Motion?.create();let nextView=0;
 for(let n=0;n<=84;n++){const t=n*1000/60;f.set(t);if(n%6===0&&n)f.m.command(1,{type:'move',x:f.m.players[1].pose.x-26,y:f.m.players[1].pose.y,generation:1,turn:1});if(t+.001>=nextView){nextView+=period;const s=f.m.snapshot(1);r.update(s,t);local?.update(s,t);}if(local)r.r.setPose(local.step(-1,t,true));const p=r.paint(t);if(t>=300){points.push(p.marker);body.push(p.body);assert(Math.abs((p.body.x-p.marker.x)-(body[0].x-points[0].x))<1,'known raster centroid follows its pose to pixel-rounding tolerance');}}
 report[period]={marker:metrics(points),body:metrics(body)};console.log(JSON.stringify({period,...report[period]}));for(const result of Object.values(report[period])){if(baseline){assert(result.movingRatio<.25);assert(result.maxStep>20);}else{assert(result.movingRatio>.9);assert(result.maxStep<6);}}
});
test('shooter masked body stays at authoritative pixel positions, without expansion',()=>{const f=fixture(),r=renderer();f.set(3200);const s=f.m.snapshot(0),before=JSON.stringify(s);r.update(s,3200);r.r.setPose?.({x:900,y:100});const p=r.paint(3250);assert.equal(p.body.offsetX,0);assert.equal(p.body.offsetY,0);assert.equal(p.body.pixels,s.pixels.length);assert.equal(p.marker,null);assert.equal(JSON.stringify(s),before);assert(!Object.hasOwn(s.opponent,'pose'));assert(!Object.hasOwn(s.opponent,'frames'));});
test('lobby before pose exists still paints without stopping the animation loop',()=>{const f=fixture(),r=renderer(),s=f.m.snapshot(1);delete s.self.pose;s.phase='lobby';r.update(s,0);assert.doesNotThrow(()=>r.paint(0));});
if(Motion){
 test('held movement is bounded; release stops immediately and old snapshots cannot pull it back',()=>{const f=fixture(),local=Motion.create();const initial=f.m.snapshot(1);local.update(initial,0);let p;for(let t=1000/60;t<=300;t+=1000/60)p=local.step(-1,t,true);const stopped=p.x;for(let t=320;t<1000;t+=20){local.update({...initial,serverTime:t},t);assert.equal(local.step(0,t,true).x,stopped);}local.update({...initial,serverTime:0},1000);assert.equal(local.step(0,1000,true).x,stopped);for(let t=1020;t<4000;t+=20)p=local.step(-1,t,true);assert(Math.abs(initial.self.pose.x-p.x)<=R.rules.speed*.5+.001);assert.equal(initial.self.pose.x,f.m.players[1].pose.x,'presentation never writes authoritative Match');});
 test('300ms snapshots plus 100ms command batches and jitter do not stall local motion',()=>{const f=fixture(),local=Motion.create();local.update(f.m.snapshot(1),0);const commands=[],views=[];let previous=local.current().x;for(let t=10;t<=1800;t+=10){f.set(t);while(commands[0]?.at<=t){const q=commands.shift();f.m.command(1,{type:'move',x:q.x,y:q.y,generation:1,turn:1});}if(t%300===0)views.push({at:t+80+(t%600?10:0),snapshot:f.m.snapshot(1)});while(views[0]?.at<=t)local.update(views.shift().snapshot,t);const p=local.step(-1,t,true);assert(previous-p.x>2.5,'normal delivery budget must advance every 10ms frame');previous=p.x;if(t%100===0&&local.needsSend())commands.push({at:t+60+(t%200?10:0),x:p.x,y:p.y});}});
 test('final target is retried until actual delayed and speed-clamped Match acknowledges it',()=>{const f=fixture(),local=Motion.create();local.update(f.m.snapshot(1),0);const queue=[];let release=null,sends=0;for(let t=10;t<=1800;t+=10){f.set(t);if(t%300===0)local.update(f.m.snapshot(1),t);const p=local.step(t<=650?-1:0,t,true);if(t===650)release=p.x;if(t%100===0&&local.needsSend()){queue.push({at:t+(t===600?10:60),x:p.x,y:p.y});sends++;}while(queue[0]?.at<=t){const q=queue.shift();f.m.command(1,{type:'move',x:q.x,y:q.y,generation:1,turn:1});}if(release!==null)assert(Math.abs(p.x-release)<.001,'key release is immediate even while referee catches up');}assert(sends>6,'a final unacknowledged position must be retried after release');assert(Math.abs(f.m.players[1].pose.x-release)<.01);assert.equal(local.needsSend(),false);});
 test('wall bounds, long frames, pause, role change and generation reset do not leak prediction',()=>{const f=fixture(),local=Motion.create(),s=f.m.snapshot(1);local.update(s,0,{minX:s.self.pose.x-5,maxX:s.self.pose.x+5});assert.equal(local.step(-1,2000,true).x,s.self.pose.x-5);local.update({...s,phase:'paused'},2010);assert.equal(local.step(-1,2020,true),null);local.update({...s,generation:2},2030);assert.equal(local.step(0,2030,true).x,s.self.pose.x);local.update({...s,hiding:false},2040);assert.equal(local.step(-1,2050,true),null);local.update(s,2060);assert.equal(local.step(-1,2070,false).x,s.self.pose.x);});
}
test.after(()=>{if(process.env.PET_DUEL_MOTION_REPORT){fs.mkdirSync(path.dirname(process.env.PET_DUEL_MOTION_REPORT),{recursive:true});fs.writeFileSync(process.env.PET_DUEL_MOTION_REPORT,JSON.stringify(report,null,2));}});
